-- GardaWarga - Supabase database
-- Jalankan seluruh file ini di Supabase SQL Editor.
-- Jangan masukkan service_role key ke frontend/GitHub.

create extension if not exists pgcrypto;

-- =========================
-- PROFILES / AKUN WARGA
-- =========================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nama text not null,
  email text unique not null,
  hp text default '-',
  rt text default '-',
  rw text default '-',
  role text not null default 'warga' check (role in ('warga','petugas')),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Membuat profile otomatis ketika user mendaftar lewat Supabase Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nama, email, hp, rt, rw, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nama', split_part(new.email, '@', 1)),
    lower(new.email),
    coalesce(new.raw_user_meta_data->>'hp', '-'),
    coalesce(new.raw_user_meta_data->>'rt', '-'),
    coalesce(new.raw_user_meta_data->>'rw', '-'),
    'warga'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- =========================
-- NOTIFIKASI
-- =========================
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  text text not null,
  type text not null default 'umum',
  read boolean not null default false,
  created_at timestamptz not null default now()
);

-- user_id NULL = notifikasi untuk semua warga.
-- user_id terisi = notifikasi khusus satu warga.

-- =========================
-- JADWAL KEGIATAN
-- =========================
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_date date not null,
  start_time time,
  end_time time,
  lokasi text not null default '-',
  deskripsi text default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- PENGADUAN
-- =========================
create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  nama text not null,
  email text not null,
  kategori text not null,
  lokasi text not null,
  deskripsi text not null,
  foto_url text,
  status text not null default 'Dikirim'
    check (status in ('Dikirim','Diterima','Diproses','Selesai')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- FORUM
-- =========================
create table if not exists public.forum_topics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  judul text not null,
  isi text not null,
  is_pinned boolean not null default false,
  is_deleted boolean not null default false,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.forum_comments (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  isi text not null,
  is_deleted boolean not null default false,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.forum_likes (
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (topic_id, user_id)
);

-- =========================
-- UPDATED_AT
-- =========================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists events_updated_at on public.events;
create trigger events_updated_at
before update on public.events
for each row execute procedure public.set_updated_at();

drop trigger if exists complaints_updated_at on public.complaints;
create trigger complaints_updated_at
before update on public.complaints
for each row execute procedure public.set_updated_at();

drop trigger if exists forum_topics_updated_at on public.forum_topics;
create trigger forum_topics_updated_at
before update on public.forum_topics
for each row execute procedure public.set_updated_at();

-- =========================
-- HELPER: CEK PETUGAS
-- =========================
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'petugas'
  );
$$;

-- =========================
-- ROW LEVEL SECURITY
-- =========================
alter table public.profiles enable row level security;
alter table public.notifications enable row level security;
alter table public.events enable row level security;
alter table public.complaints enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_comments enable row level security;
alter table public.forum_likes enable row level security;

-- PROFILES
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "profiles_update_own_or_staff" on public.profiles;
create policy "profiles_update_own_or_staff"
on public.profiles for update
to authenticated
using (id = auth.uid() or public.is_staff())
with check (id = auth.uid() or public.is_staff());

-- NOTIFICATIONS
drop policy if exists "notifications_select_own_or_global" on public.notifications;
create policy "notifications_select_own_or_global"
on public.notifications for select
to authenticated
using (user_id is null or user_id = auth.uid() or public.is_staff());

drop policy if exists "notifications_insert_staff" on public.notifications;
create policy "notifications_insert_staff"
on public.notifications for insert
to authenticated
with check (public.is_staff());

drop policy if exists "notifications_update_own_or_staff" on public.notifications;
create policy "notifications_update_own_or_staff"
on public.notifications for update
to authenticated
using (user_id = auth.uid() or public.is_staff())
with check (user_id = auth.uid() or public.is_staff());

drop policy if exists "notifications_delete_staff" on public.notifications;
create policy "notifications_delete_staff"
on public.notifications for delete
to authenticated
using (public.is_staff());

-- EVENTS / JADWAL
drop policy if exists "events_select_authenticated" on public.events;
create policy "events_select_authenticated"
on public.events for select
to authenticated
using (true);

drop policy if exists "events_insert_staff" on public.events;
create policy "events_insert_staff"
on public.events for insert
to authenticated
with check (public.is_staff());

drop policy if exists "events_update_staff" on public.events;
create policy "events_update_staff"
on public.events for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "events_delete_staff" on public.events;
create policy "events_delete_staff"
on public.events for delete
to authenticated
using (public.is_staff());

-- COMPLAINTS / PENGADUAN
drop policy if exists "complaints_select_own_or_staff" on public.complaints;
create policy "complaints_select_own_or_staff"
on public.complaints for select
to authenticated
using (user_id = auth.uid() or public.is_staff());

drop policy if exists "complaints_insert_own" on public.complaints;
create policy "complaints_insert_own"
on public.complaints for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "complaints_update_staff" on public.complaints;
create policy "complaints_update_staff"
on public.complaints for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "complaints_delete_own_or_staff" on public.complaints;
create policy "complaints_delete_own_or_staff"
on public.complaints for delete
to authenticated
using (user_id = auth.uid() or public.is_staff());

-- FORUM TOPICS
drop policy if exists "forum_topics_select_authenticated" on public.forum_topics;
create policy "forum_topics_select_authenticated"
on public.forum_topics for select
to authenticated
using (true);

drop policy if exists "forum_topics_insert_own" on public.forum_topics;
create policy "forum_topics_insert_own"
on public.forum_topics for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "forum_topics_update_own_or_staff" on public.forum_topics;
create policy "forum_topics_update_own_or_staff"
on public.forum_topics for update
to authenticated
using (user_id = auth.uid() or public.is_staff())
with check (user_id = auth.uid() or public.is_staff());

drop policy if exists "forum_topics_delete_staff" on public.forum_topics;
create policy "forum_topics_delete_staff"
on public.forum_topics for delete
to authenticated
using (public.is_staff());

-- FORUM COMMENTS
drop policy if exists "forum_comments_select_authenticated" on public.forum_comments;
create policy "forum_comments_select_authenticated"
on public.forum_comments for select
to authenticated
using (true);

drop policy if exists "forum_comments_insert_own" on public.forum_comments;
create policy "forum_comments_insert_own"
on public.forum_comments for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "forum_comments_update_own_or_staff" on public.forum_comments;
create policy "forum_comments_update_own_or_staff"
on public.forum_comments for update
to authenticated
using (user_id = auth.uid() or public.is_staff())
with check (user_id = auth.uid() or public.is_staff());

drop policy if exists "forum_comments_delete_staff" on public.forum_comments;
create policy "forum_comments_delete_staff"
on public.forum_comments for delete
to authenticated
using (public.is_staff());

-- FORUM LIKES
drop policy if exists "forum_likes_select_authenticated" on public.forum_likes;
create policy "forum_likes_select_authenticated"
on public.forum_likes for select
to authenticated
using (true);

drop policy if exists "forum_likes_insert_own" on public.forum_likes;
create policy "forum_likes_insert_own"
on public.forum_likes for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "forum_likes_delete_own_or_staff" on public.forum_likes;
create policy "forum_likes_delete_own_or_staff"
on public.forum_likes for delete
to authenticated
using (user_id = auth.uid() or public.is_staff());

-- =========================
-- INDEX
-- =========================
create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_notifications_created_at on public.notifications(created_at desc);
create index if not exists idx_events_event_date on public.events(event_date);
create index if not exists idx_complaints_user_id on public.complaints(user_id);
create index if not exists idx_complaints_status on public.complaints(status);
create index if not exists idx_forum_topics_created_at on public.forum_topics(created_at desc);
create index if not exists idx_forum_comments_topic_id on public.forum_comments(topic_id);

-- =========================
-- DATA AWAL JADWAL
-- =========================
insert into public.events (title, event_date, start_time, end_time, lokasi, deskripsi)
select '🧹 Kerja Bakti Bersih Lingkungan', '2026-09-20', '07:00', '10:00', 'RT 01–05', 'Bawa sapu, ember, dan kantong sampah.'
where not exists (
  select 1 from public.events where title = '🧹 Kerja Bakti Bersih Lingkungan' and event_date = '2026-09-20'
);

insert into public.events (title, event_date, start_time, lokasi, deskripsi)
select '📋 Rapat Warga Bulanan', '2026-09-28', '19:00', 'Balai Warga', 'Evaluasi kebersihan & rencana Oktober.'
where not exists (
  select 1 from public.events where title = '📋 Rapat Warga Bulanan' and event_date = '2026-09-28'
);

insert into public.events (title, event_date, start_time, end_time, lokasi, deskripsi)
select '♻️ Pelatihan Pengelolaan Sampah Organik', '2026-10-04', '09:00', '12:00', 'Aula Desa', 'Narasumber Dinas Lingkungan Hidup.'
where not exists (
  select 1 from public.events where title = '♻️ Pelatihan Pengelolaan Sampah Organik' and event_date = '2026-10-04'
);

insert into public.events (title, event_date, start_time, lokasi, deskripsi)
select '🌳 Penanaman Pohon di Tepi Sungai', '2026-10-12', '07:30', null, 'Bantaran sungai', 'Bibit disediakan panitia.'
where not exists (
  select 1 from public.events where title = '🌳 Penanaman Pohon di Tepi Sungai' and event_date = '2026-10-12'
);
